// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package gosystem is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	ResultCommand
*/
package gosystem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultCommand struct {
	Command       string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	ResultCommand string `protobuf:"bytes,2,opt,name=result_command,json=resultCommand" json:"result_command,omitempty"`
	ReturnCode    int32  `protobuf:"varint,3,opt,name=return_code,json=returnCode" json:"return_code,omitempty"`
}

func (m *ResultCommand) Reset()                    { *m = ResultCommand{} }
func (m *ResultCommand) String() string            { return proto.CompactTextString(m) }
func (*ResultCommand) ProtoMessage()               {}
func (*ResultCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResultCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ResultCommand) GetResultCommand() string {
	if m != nil {
		return m.ResultCommand
	}
	return ""
}

func (m *ResultCommand) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ResultCommand)(nil), "gosystem.result_command")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcf, 0x2f, 0xae, 0x2c,
	0x2e, 0x49, 0xcd, 0x55, 0x2a, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x89, 0x4f, 0xce,
	0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x92, 0xe0, 0x62, 0x87, 0x32, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x60, 0x5c, 0x21, 0x55, 0x74, 0xb5, 0x12, 0x4c, 0x60, 0x05, 0xbc, 0x10, 0x51, 0x67,
	0xa8, 0x32, 0x79, 0x2e, 0xee, 0xa2, 0xd4, 0x92, 0xd2, 0xa2, 0xbc, 0xf8, 0xe4, 0xfc, 0x94, 0x54,
	0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x2e, 0x88, 0x90, 0x73, 0x7e, 0x4a, 0x6a, 0x12, 0x1b,
	0xd8, 0x11, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x44, 0x69, 0xf0, 0x95, 0x00, 0x00,
	0x00,
}
